password: your password
test_interval:
- test: ping
  type: sec
  duration: 3
- test: jitter
  type: min
  duration: 5
- test: req-res-delay-and-monitoring
  type: sec
  duration: 15
routes:
- method: GET
  url: https://www.google.co.in
  route: search
  headers:
  - type: Content-Type
    value: application/json
  params:
  - name: q
    value: bench-routes
utils:
  response-length:
    mode: 0
    mean: 0
  services-state:
    ping: passive
    flood-ping: passive
    jitter: passive
    req-res-deplay-or-monitoring: passive
