# This workflow will build bench routes
# on the darwin platform
name: continuous-integeration/darwin

on: [pull_request, push]

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update homebrew
        run: brew update
      - name: Install dependencies
        run: |
            brew install node
            npm install -g yarn
            brew install golangci/tap/golangci-lint
            brew upgrade golangci/tap/golangci-lint
      - name: Lint for errors
        run: golangci-lint run --timeout=10m
      - name: Update make
        run: make update
      - name: Build the frontend
        run: make build-frontend
      - name: Build bench routes
        run: make build
      - name: Run the test suite
        run: make test
